config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('poll/', include('poll.urls')),
    path('admin/', admin.site.urls),
]

poll/urls.py
from django.urls import path
from . import views

# 네임스페이스 설정
# urls.py에 [app_name]이라는 변수를 추가하고 이름을 설정하면 네임스페이스 설정은 완료.
# 이 네임스페이스를 사용하기 위해서 템플릿에도 수정을 해야함.
app_name = 'poll'


# 클래스형 뷰로 변경한 코드
# 아래 함수형 뷰와 다른 점은,
# route 패턴에 들어있는 패턴이름과 view 인자
# 패턴이름을 question_id에서 pk로 변경했음. 그리고 뷰 이름을 바꾸고 뒤에 추가 코드를 붙임.
# 함수형 뷰를 사용할 떄는 뷰를 그대로 써주면 되지만 클래스형 뷰를 사용할 떄는 꼭 뒤에 [as_view()]를 붙여야 하기 때문임.
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]



# 함수형 뷰
# urlpatterns = [
#     #poll/views.py가 작동하도록 아래에 URL을 연결
#
#     # ex: /poll/
#     path('', views.index, name='index'),
#
#     # ex: /poll/5/
#     path('<int:question_id>/', views.detail, name='detail'),    #<>(화살괄호)는 변수를 의미
#
#     # ex: /poll/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#
#     # ex: /poll/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote')
# ]

poll/models.py
import datetime

from django.db import models
from django.utils import timezone
#

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date' # 원칙적으로 임의의 메서드에 의한 값은 정렬이 불가능함. 대신 다른 값을 기준으로 정렬할 수 있는데 이 기준 항목을 설정하는 항목
    was_published_recently.boolean = True # 값이 불리언 값 형태인지 설정. True 설정하면 값 대신 아이콘이 나타남.
    was_published_recently.short_description = 'Published recently?' # 항목의 헤더 이름 설정.

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

poll/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.template import loader  #템플릿을 불러오기 위해 loader 임포트
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published question"""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'



#인덱스 화면 출력
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]   #질문 리스트 5개만 가져오기

    # 1.render 메서드를 사용하지 않고 아래와 같이 코드 작성 가능
#    template = loader.get_template('polls/index.html')  # .html 템플릿 연결하기
#    context = { #latest_question_list(투표목록) 변수를 전달하기 위한 context
#       'latest_question_list':latest_question_list,
#    }
#     return HttpResponse(template.render(context, request))

    # 2.위 방법이 번거롭게 느껴진다면 render 메서드를 활용해서 아래와 같이 작성 가능
#    context = { 'latest_question_list': latest_question_list } # latest_question_list(투표목록) 변수를 전달하기 위한 context
#    return render(request, 'polls/index.html', context)

    # output = ', '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)


#투표 상세 화면 출력
#def detail(request, question_id): #특별한 결과 없이 값만 출력
    # 1. 투표 상세 목록을 불러옴. 불러올 항목이 없을 경우 404 에러를 발생시킨다.
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise  Http404("Question does not exist")
    # return render(request, 'polls/detail.html', {'question':question})

    # 2. get_object_or_404 메서드를 활용해 위의 코드를 간소화 시킬 수 있다.
 #   question = get_object_or_404(Question, pk=question_id)
 #   return render(request, 'polls/detail.html', {'question':question})

    # return HttpResponse("You're looking at question %s." % question_id)

#투표 결과 화면 출력
#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/results.html', {'question':question})

#투표 기능 화면 출력
def vote(request, question_id): #특별한 결과 없이 값만 출력
    question = get_object_or_404(Question, pk=question_id)

    try:
        # request.POST[변수이름]을 통해 전달받은 변수의 값들을 확인할 수 있음. 이떄 전달되는 값은 문자열.
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        # 전달받은 답변이 해당 투표 항목에 있는지 확인하고 없다면 다시 상세페이지로 이동
        # 이 때 답변을 선택하지 않았다는 오류 메시기 같이 전달
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message' : "You didn't select a choice."
    })
    else:
        # 제대로된 답변을 선택한 것이라면 해당 답변의 답변수를 1 증가 시키고 결과 화면으로 이동
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

poll/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>



{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- [form]태그를 사용해서 사용자가 답변 항목을 선택/전달 할 수 있도록 -->
<!-- 사용자가 선택한 항목의 번호를 vote 뷰를 전달하도록 action 속성에 vote URL이 출력되게 url 템플릿 태그를 사용 -->

<form action="{% url 'poll:vote' question.id %}" method="post"> <!-- method 속성의 post는 HTTP메서드중 하나이며 서버로 정보를 전달할 때 사용 -->
<!-- csrf_token은 CSRF 공격을 막기 위한 수단 중 하나. => 방금 서버로 들어온 요청이 사이트 내부에서 온 것이 맞는지 확인하는 용도-->
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <!-- forlopp.counter는 템플릿 문법에서 제공하는 기능 중 하나로 반복문의 반복 횟수를 출력.
    여기서 선택한 답변의 번호를 vote뷰에 [choice=번호] 형태로 전달. -->
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>


</body>
</html>

poll/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load static %} <!-- static 파일 css 로드하기 -->
    <link ref="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <!-- 이 코드는 URL이 하드코딩된 방식
            <li><a href="/poll/{{ question.id }}/">{{ question.question_text }}</a></li>
            -->

            <!-- 위의 하드코딩된 URL을 아래와 같이 바꿈. 아래는 url 템플릿 태그를 사용해 주소를 출력 -->
            <!-- url 템플릿 태그는 URL의 이름을 필수 인자로 전달 받음. detail 이라는 이름을 가진 URL 형식을 찾아서 URL을 만들어 출력(해당 이름은 urls.py 전체를 검색하여 찾음) -->
            <!-- 아래 'poll:detail'은 네임스페이스를 사용한 코드 -->
            <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}
</body>
</html>

poll/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- results.html은 각 답변 항목과 투표 수를 한꺼번에 보여준다 -->
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize}}</li><!-- pluralize:복수로 만드는 필터 -->
{% endfor %}
</ul>


<a href="{% url 'poll:detail' question.id %}">vote again?</a>
</body>
</html>